
import java.awt.Color;
import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Keerat666
 */
public class t3UI extends javax.swing.JFrame {

    /**
     * Creates new form t3UI
     */
     int ctr=0;
     boolean win=false;
     String winner="";
     
    public t3UI() {
        initComponents();
                   
              jLabel1.setText(1+" 's Turn ");
             

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
  boolean row(int x, String n)
    {
       
        boolean flag=false;

        if(x==0) 
        {
            String a = jButton0.getText();
            String b = jButton1.getText();
            String c = jButton2.getText();
            if(a.equals(n) && b.equals(n) && c.equals(n))
            {
                flag=true;
                jButton0.setBackground(Color.GREEN);
                jButton1.setBackground(Color.GREEN);
                jButton2.setBackground(Color.GREEN);
            }
        }
        
        if(x==1) 
        {
            String a = jButton3.getText();
            String b = jButton4.getText();
            String c = jButton5.getText();
            if(a.equals(n) && b.equals(n) && c.equals(n))
            {
                flag=true;
                jButton3.setBackground(Color.GREEN);
                jButton4.setBackground(Color.GREEN);
                jButton5.setBackground(Color.GREEN);
            }
        }
        
        if(x==2) 
        {
            String a = jButton6.getText();
            String b = jButton7.getText();
            String c = jButton8.getText();
            if(a.equals(n) && b.equals(n) && c.equals(n))
            {
                flag=true;
                 jButton6.setBackground(Color.GREEN);
                 jButton7.setBackground(Color.GREEN);
                 jButton8.setBackground(Color.GREEN);
            }
           
        }
        

        return flag;
    }
  
     boolean col(int y, String n)
    {
       
        boolean flag=false;

        if(y==0) 
        {
            String a = jButton0.getText();
            String b = jButton3.getText();
            String c = jButton6.getText();
            if(a.equals(n) && b.equals(n) && c.equals(n))
            {
                flag=true;
                jButton6.setBackground(Color.GREEN);
                jButton0.setBackground(Color.GREEN);
                jButton3.setBackground(Color.GREEN);
            }
        }
        
        if(y==1) 
        {
            String a = jButton1.getText();
            String b = jButton4.getText();
            String c = jButton7.getText();
            if(a.equals(n) && b.equals(n) && c.equals(n))
            {
                flag=true;
                jButton1.setBackground(Color.GREEN);
                jButton4.setBackground(Color.GREEN);
                jButton7.setBackground(Color.GREEN);
            }
                
        }
        
        if(y==2) 
        {
            String a = jButton2.getText();
            String b = jButton5.getText();
            String c = jButton8.getText();
            if(a.equals(n) && b.equals(n) && c.equals(n))
            { 
                flag=true;
                jButton2.setBackground(Color.GREEN);
                jButton5.setBackground(Color.GREEN);
                jButton8.setBackground(Color.GREEN);
            
            }
        }
        

        return flag;
    }
   boolean rdiag(String n)
    {
        boolean flag=false;
            String a = jButton2.getText();
            String b = jButton4.getText();
            String c = jButton6.getText();
            if(a.equals(n) && b.equals(n) && c.equals(n))
            {
                flag=true;
                jButton2.setBackground(Color.GREEN);
                jButton4.setBackground(Color.GREEN);
                jButton6.setBackground(Color.GREEN);
                
            }
        return flag;
        

        }
   
     boolean ldiag(String n)
    {
        boolean flag=false;
            String a = jButton0.getText();
            String b = jButton4.getText();
            String c = jButton8.getText();
            if(a.equals(n) && b.equals(n) && c.equals(n))
            {
                flag=true;
                jButton0.setBackground(Color.GREEN);
                jButton4.setBackground(Color.GREEN);
                jButton8.setBackground(Color.GREEN);
            
            }
        return flag;
        

        }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton0 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.magenta);
        setType(java.awt.Window.Type.POPUP);

        jButton0.setBackground(new java.awt.Color(0, 0, 0));
        jButton0.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton0.setForeground(new java.awt.Color(255, 255, 255));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
                     boolean checka1 = false;
       boolean checka2=false;
       boolean checka3 = false;
       boolean checka4=false;
       boolean checkb1 = false;
       boolean checkb2=false;
      boolean checkb3 = false;
       boolean checkb4=false;
       String a = jButton0.getText();
       int sl=a.length();
       if(sl==0 && ctr!=9 && win==false)
       {
        if(ctr%2==0)
        {
            jButton0.setText("X");
               checka1=row(0,"X");
               checka2=col(0,"X");
               checka3=rdiag("X");
               checka4=ldiag("X");
            
        }
        else
        {
            jButton0.setText("O");
               checkb1=row(0,"O");
               checkb2=col(0,"O");
               checkb3=rdiag("O");
               checkb4=ldiag("O");
            
               
            
        }
                if(checka1 || checka2 || checka3 || checka4)
                {
                    jLabel1.setText("Player 1 won");
                    win=true;
                    winner="Player 1 ";
                }
                
                else if(checkb1 || checkb2 || checkb3 || checkb4)
                {
                    jLabel1.setText("Player 2 won");
                    win=true;
                    winner="Player 2 ";
                }
                 
                else
                {
                  ctr++;
                  if(ctr<=8 && win==false)
                jLabel1.setText((ctr%2)+1+" 's Turn ");
                 
                  
                  if(ctr==9 && win==false)
                 {
                     jButton0.setText("X");
                    jLabel1.setText("Game Draw !");
                    ctr++;
                 }
                      

                }
        
       }
       else if(win==true)
           jLabel1.setText("Start over the game. "+winner +"already won the game .");
       else if(ctr==9)
            jLabel1.setText("Start over the game . The game was a Draw .");
        
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         boolean checka1 = false;
       boolean checka2=false;
       boolean checka3 = false;
       boolean checka4=false;
       boolean checkb1 = false;
       boolean checkb2=false;
      boolean checkb3 = false;
       boolean checkb4=false;
       String a = jButton6.getText();
       int sl=a.length();
       if(sl==0 && ctr!=9 && win==false)
       {
        if(ctr%2==0)
        {
            jButton6.setText("X");
               checka1=row(2,"X");
               checka2=col(0,"X");
               checka3=rdiag("X");
               checka4=ldiag("X");
            
        }
        else
        {
            jButton6.setText("O");
               checkb1=row(2,"O");
               checkb2=col(0,"O");
               checkb3=rdiag("O");
               checkb4=ldiag("O");
            
               
            
        }
                if(checka1 || checka2 || checka3 || checka4)
                {
                    jLabel1.setText("Player 1 won");
                    win=true;
                    winner="Player 1 ";
                }
                
                else if(checkb1 || checkb2 || checkb3 || checkb4)
                {
                    jLabel1.setText("Player 2 won");
                    win=true;
                    winner="Player 2 ";
                }
                else
                {
                  ctr++;
                 if(ctr<=8 && win==false)
                jLabel1.setText((ctr%2)+1+" 's Turn ");
                 
                  
                  if(ctr==9 && win==false)
                 {
                     jButton6.setText("X");
                    jLabel1.setText("Game Draw !");
                    ctr++;
                 }

                }
        
       }
       
       else if(win==true)
           jLabel1.setText("Start over the game. "+winner +"already won the game .");
       else if(ctr==9)
            jLabel1.setText("Start over the game . The game was a Draw .");
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       boolean checka1 = false;
       boolean checka2=false;
       boolean checka3 = false;
       boolean checka4=false;
       boolean checkb1 = false;
       boolean checkb2=false;
       boolean checkb3 = false;
       boolean checkb4=false;
       String a = jButton3.getText();
       int sl=a.length();
       if(sl==0 && ctr!=9 && win==false)
       {
        if(ctr%2==0)
        {
            jButton3.setText("X");
               checka1=row(1,"X");
               checka2=col(0,"X");
               checka3=rdiag("X");
               checka4=ldiag("X");
            
        }
        else
        {
            jButton3.setText("O");
               checkb1=row(1,"O");
               checkb2=col(0,"O");
               checkb3=rdiag("O");
               checkb4=ldiag("O");
            
               
            
        }
                if(checka1 || checka2 || checka3 || checka4)
                {
                    jLabel1.setText("Player 1 won");
                    win=true;
                    winner="Player 1 ";
                }
                
                else if(checkb1 || checkb2 || checkb3 || checkb4)
                {
                    jLabel1.setText("Player 2 won");
                    win=true;
                    winner="Player 2 ";
                }
                else
                {
                  ctr++;
                 if(ctr<=8 && win==false)
                jLabel1.setText((ctr%2)+1+" 's Turn ");
                 
                  
                  if(ctr==9 && win==false)
                 {
                     jButton6.setText("X");
                    jLabel1.setText("Game Draw !");
                    ctr++;
                 }

                }
        
       }
       
       else if(win==true)
           jLabel1.setText("Start over the game. "+winner +"already won the game .");
       else if(ctr==9)
           jLabel1.setText("Start over the game . The game was a Draw .");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       boolean checka1 = false;
       boolean checka2=false;
       boolean checka3 = false;
       boolean checka4=false;
       boolean checkb1 = false;
       boolean checkb2=false;
       boolean checkb3 = false;
       boolean checkb4=false;
       String a = jButton1.getText();
       int sl=a.length();
       if(sl==0 && ctr!=9 && win==false)
       {
        if(ctr%2==0)
        {
            jButton1.setText("X");
               checka1=row(0,"X");
               checka2=col(1,"X");
               checka3=rdiag("X");
               checka4=ldiag("X");
            
        }
        else
        {
            jButton1.setText("O");
               checkb1=row(0,"O");
               checkb2=col(1,"O");
               checkb3=rdiag("O");
               checkb4=ldiag("O");
            
               
            
        }
                if(checka1 || checka2 || checka3 || checka4)
                {
                    jLabel1.setText("Player 1 won");
                    win=true;
                    winner="Player 1 ";
                }
                
                else if(checkb1 || checkb2 || checkb3 || checkb4)
                {
                    jLabel1.setText("Player 2 won");
                    win=true;
                    winner="Player 2 ";
                }
                else
                {
                  ctr++;
                 if(ctr<=8 && win==false)
                jLabel1.setText((ctr%2)+1+" 's Turn ");
                 
                  
                  if(ctr==9 && win==false)
                 {
                     jButton1.setText("X");
                    jLabel1.setText("Game Draw !");
                    ctr++;
                 }

                }
        
       }
       
       else if(win==true)
           jLabel1.setText("Start over the game. "+winner +"already won the game .");
       else if(ctr==9)
            jLabel1.setText("Start over the game . The game was a Draw .");

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       boolean checka1 = false;
       boolean checka2=false;
       boolean checka3 = false;
       boolean checka4=false;
       boolean checkb1 = false;
       boolean checkb2=false;
      boolean checkb3 = false;
       boolean checkb4=false;
       String a = jButton7.getText();
       int sl=a.length();
       if(sl==0 && ctr!=9 && win==false)
       {
        if(ctr%2==0)
        {
            jButton7.setText("X");
               checka1=row(2,"X");
               checka2=col(1,"X");
               checka3=rdiag("X");
               checka4=ldiag("X");
            
        }
        else
        {
            jButton7.setText("O");
               checkb1=row(2,"O");
               checkb2=col(1,"O");
               checkb3=rdiag("O");
               checkb4=ldiag("O");
            
               
            
        }
                if(checka1 || checka2 || checka3 || checka4)
                {
                    jLabel1.setText("Player 1 won");
                    win=true;
                    winner="Player 1 ";
                }
                
                else if(checkb1 || checkb2 || checkb3 || checkb4)
                {
                    jLabel1.setText("Player 2 won");
                    win=true;
                    winner="Player 2 ";
                }
                else
                {
                  ctr++;
                  if(ctr<=8 && win==false)
                jLabel1.setText((ctr%2)+1+" 's Turn ");
                 
                  
                  if(ctr==9 && win==false)
                 {
                     jButton7.setText("X");
                    jLabel1.setText("Game Draw !");
                    ctr++;
                 }

                }
        
       }
      
       else if(win==true)
           jLabel1.setText("Start over the game. "+winner +"already won the game .");
       else if(ctr==9)
            jLabel1.setText("Start over the game . The game was a Draw .");
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                        boolean checka1 = false;
       boolean checka2=false;
       boolean checka3 = false;
       boolean checka4=false;
       boolean checkb1 = false;
       boolean checkb2=false;
      boolean checkb3 = false;
       boolean checkb4=false;
       String a = jButton4.getText();
       int sl=a.length();
       if(sl==0 && ctr!=9 && win==false)
       {
        if(ctr%2==0)
        {
            jButton4.setText("X");
               checka1=row(1,"X");
               checka2=col(1,"X");
               checka3=rdiag("X");
               checka4=ldiag("X");
            
        }
        else
        {
            jButton4.setText("O");
               checkb1=row(1,"O");
               checkb2=col(1,"O");
               checkb3=rdiag("O");
               checkb4=ldiag("O");
            
               
            
        }
                if(checka1 || checka2 || checka3 || checka4)
                {
                    jLabel1.setText("Player 1 won");
                    win=true;
                    winner="Player 1 ";
                }
                
                else if(checkb1 || checkb2 || checkb3 || checkb4)
                {
                    jLabel1.setText("Player 2 won");
                    win=true;
                    winner="Player 2 ";
                }
                else
                {
                  ctr++;
                 if(ctr<=8 && win==false)
                jLabel1.setText((ctr%2)+1+" 's Turn ");
                 
                  
                  if(ctr==9 && win==false)
                 {
                     jButton4.setText("X");
                    jLabel1.setText("Game Draw !");
                    ctr++;
                 }

                }
        
       }
      
       else if(win==true)
           jLabel1.setText("Start over the game. "+winner +"already won the game .");
       else if(ctr==9)
           jLabel1.setText("Start over the game . The game was a Draw .");
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                              boolean checka1 = false;
       boolean checka2=false;
       boolean checka3 = false;
       boolean checka4=false;
       boolean checkb1 = false;
       boolean checkb2=false;
      boolean checkb3 = false;
       boolean checkb4=false;
       String a = jButton2.getText();
       int sl=a.length();
       if(sl==0 && ctr!=9 && win==false)
       {
        if(ctr%2==0)
        {
            jButton2.setText("X");
               checka1=row(0,"X");
               checka2=col(2,"X");
               checka3=rdiag("X");
               checka4=ldiag("X");
            
        }
        else
        {
            jButton2.setText("O");
               checkb1=row(0,"O");
               checkb2=col(2,"O");
               checkb3=rdiag("O");
               checkb4=ldiag("O");
            
               
            
        }
                if(checka1 || checka2 || checka3 || checka4)
                {
                    jLabel1.setText("Player 1 won");
                    win=true;
                    winner="Player 1 ";
                }
                
                else if(checkb1 || checkb2 || checkb3 || checkb4)
                {
                    jLabel1.setText("Player 2 won");
                    win=true;
                    winner="Player 2 ";
                }
                else
                {
                  ctr++;
                if(ctr<=8 && win==false)
                jLabel1.setText((ctr%2)+1+" 's Turn ");
                 
                  
                  if(ctr==9 && win==false)
                 {
                     jButton2.setText("X");
                    jLabel1.setText("Game Draw !");
                    ctr++;
                 }

                }
        
       }
      
       else if(win==true)
           jLabel1.setText("Start over the game. "+winner +"already won the game .");
       else if(ctr==9)
           jLabel1.setText("Start over the game . The game was a Draw .");

        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
                            boolean checka1 = false;
       boolean checka2=false;
       boolean checka3 = false;
       boolean checka4=false;
       boolean checkb1 = false;
       boolean checkb2=false;
      boolean checkb3 = false;
       boolean checkb4=false;
       String a = jButton8.getText();
       int sl=a.length();
       if(sl==0 && ctr!=9 && win==false)
       {
        if(ctr%2==0)
        {
            jButton8.setText("X");
               checka1=row(2,"X");
               checka2=col(2,"X");
               checka3=rdiag("X");
               checka4=ldiag("X");
            
        }
        else
        {
            jButton8.setText("O");
               checkb1=row(2,"O");
               checkb2=col(2,"O");
               checkb3=rdiag("O");
               checkb4=ldiag("O");
            
               
            
        }
                if(checka1 || checka2 || checka3 || checka4)
                {
                    jLabel1.setText("Player 1 won");
                    win=true;
                    winner="Player 1 ";
                }
                
                else if(checkb1 || checkb2 || checkb3 || checkb4)
                {
                    jLabel1.setText("Player 2 won");
                    win=true;
                    winner="Player 2 ";
                }
                else
                {
                  ctr++;
                if(ctr<=8 && win==false)
                jLabel1.setText((ctr%2)+1+" 's Turn ");
                 
                  
                  if(ctr==9 && win==false)
                 {
                     jButton8.setText("X");
                    jLabel1.setText("Game Draw !");
                    ctr++;
                 }

                }
        
       }
       
       else if(win==true)
           jLabel1.setText("Start over the game. "+winner +"already won the game .");
       else if(ctr==9)
           jLabel1.setText("Start over the game . The game was a Draw .");
      
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                            boolean checka1 = false;
       boolean checka2=false;
       boolean checka3 = false;
       boolean checka4=false;
       boolean checkb1 = false;
       boolean checkb2=false;
      boolean checkb3 = false;
       boolean checkb4=false;
       String a = jButton5.getText();
       int sl=a.length();
       if(sl==0 && ctr!=9 && win==false)
       {
        if(ctr%2==0)
        {
            jButton5.setText("X");
               checka1=row(1,"X");
               checka2=col(2,"X");
               checka3=rdiag("X");
               checka4=ldiag("X");
            
        }
        else
        {
            jButton5.setText("O");
               checkb1=row(1,"O");
               checkb2=col(2,"O");
               checkb3=rdiag("O");
               checkb4=ldiag("O");
            
               
            
        }
                if(checka1 || checka2 || checka3 || checka4)
                {
                    jLabel1.setText("Player 1 won");
                    win=true;
                    winner="Player 1 ";
                }
                
                else if(checkb1 || checkb2 || checkb3 || checkb4)
                {
                    jLabel1.setText("Player 2 won");
                    win=true;
                    winner="Player 2 ";
                }
                else
                {
                  ctr++;
                 if(ctr<=8 && win==false)
                jLabel1.setText((ctr%2)+1+" 's Turn ");
                 
                  
                  if(ctr==9 && win==false)
                 {
                     jButton5.setText("X");
                    jLabel1.setText("Game Draw !");
                    ctr++;
                 }

                }
        
       }
       
       else if(win==true)
           jLabel1.setText("Start over the game. "+winner +"already won the game .");
       else if(ctr==9)
           jLabel1.setText("Start over the game . The game was a Draw .");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(t3UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(t3UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(t3UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(t3UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new t3UI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
